# Generated by Django 2.1.5 on 2019-02-07 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('date_start_time', models.DateTimeField(default=datetime.datetime(2019, 2, 7, 14, 4, 10, 850755))),
                ('points', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('year', models.IntegerField(default=2019, verbose_name='year')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('prev_year_rank', models.IntegerField(default=-1)),
                ('cur_year_rank', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='opp_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opp_team', to='main.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.Team'),
        ),
    ]
