# Generated by Django 2.1.5 on 2019-02-14 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('opp_team', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=-1)),
                ('opp_points', models.IntegerField(default=-1)),
                ('date_start_time', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 14, 28, 3, 494699))),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Team_RPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('rpi', models.IntegerField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='opp_team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cur_year_rank',
        ),
        migrations.RemoveField(
            model_name='team',
            name='prev_year_rank',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
