# Generated by Django 2.1.5 on 2019-04-01 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190214_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_info',
            name='date_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 19, 14, 52, 789022)),
        ),
    ]
