# Generated by Django 2.1.5 on 2019-04-01 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190331_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_info',
            name='date_start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 20, 55, 55, 625300)),
        ),
    ]
